### ISSUE TITLE
Upgrade ES to 7.13

### ISSUE THREAD

**Issue by Zaszczyk** [allegro/elasticsearch-analysis-morfologik#20]
Please upgrade ElasticSearch to version 7.13, because earlier verions are not supported on Apple Silicon/M1.

**Comment by sebastianwos** [comment]
Podpinam się pod powyższe - czy można liczyć na podniesienie wspieranej wersji do 7.13

**Comment by jackraymund** [comment]
A najlepiej do 7.15 :<<

**Comment by arturnow** [comment]
Minim do 7.16.2  z powodu Log4j

**Comment by allepbo** [comment]
After a long break, the mechanism for publishing elasticsearch-analysis-morphologik to maven central has been repaired.

New releases: 
7.16.1 - for elasticsearch 7.16.1
7.16.2.1 - for elasticsearch 7.16.2
7.16.3 - for elasticsearch 7.16.3

**Comment by scoro** [comment]
Thanks a lot Paweł ;-)
