### ISSUE TITLE
IllegalAccessException for ES 2.4.4

### ISSUE THREAD

**Issue by evgfedko** [allegro/elasticsearch-analysis-morfologik#3]
I am currently trying to use morfologik for ES 2.4.4. I use the following settings for the index:

```json{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 1,
      "analysis": {
        "filter": {
        },
        "analyzer": {
          "fulltext": {
            "type": "morfologik",
            "tokenizer": "standard",
            "filter": [
              "lowercase"
            ]
          }
        }
      }
    }
  }
}
```

But when I try to create the index, i get
`java.lang.IllegalAccessException: Class org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1 can not access a member of class pl.allegro.tech.elasticsearch.index.analysis.pl.MorfologikAnalyzerProvider with modifiers "public"`

**Comment by pbobruk** [comment]
Hi,

Morfologik analyzer doesn't support any configuration options like for example "standard analyzer" have option "stopwords":
https://www.elastic.co/guide/en/elasticsearch/guide/current/using-stopwords.html#_stopwords_and_the_standard_analyzer

In your example, you are trying to pass special configuration options to the Morfologik analyzer, so, think that You want to do this:
```
  "analyzer": {
    "fulltext": {
      "tokenizer": "standard",
      "filter": [
        "lowercase", "morfologik_stem"
      ]
    }
  }
```
Analyzer "fulltext" will have standard tokenizer and filter with morphological analysis.

You can also use "morfologik" analyzer directly in mapping.

**Comment by evgfedko** [comment]
@pbobruk Thank you, my fault! Works as you described. Sorry for the inconvenience.
