### ISSUE TITLE
Elasticsearch 7.17.8

### ISSUE THREAD

**Issue by soczil** [allegro/elasticsearch-analysis-morfologik#41]
Hi, could you please release version compatible with elasticsearch 7.17.8?

**Comment by maciekstary** [comment]
@soczil version 7.17.8 is present in the repository:
https://repo1.maven.org/maven2/pl/allegro/tech/elasticsearch/plugin/elasticsearch-analysis-morfologik/7.17.8/

What is really lacking is version 7.17.9 and that's what I would ask for.

**Comment by allepbo** [comment]
Hi, done, version 7.17.9 has just been released.

**Comment by maciekstary** [comment]
@allepbo Great, thank you!! :-)
