### ISSUE TITLE
lowercase + morfologik_stem dosen't work for proper names

### ISSUE THREAD

**Issue by apohllo** [allegro/elasticsearch-analysis-morfologik#6]
With the following mapping:

```json
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "morfologik_downcase": {
           "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "morfologik_stem"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "message": {
      "properties": {
        "content":          { "type": "text", "analyzer": "morfologik_downcase"}
      }
    }
  }
}
```

The following analysis:

```
curl -XGET http://localhost:9200/index_name/_analyze -d '{"analyzer": "morfologik_downcase", "text": "Kwaśniewskiego" }' -H "Content-type: application/json" -H "Accept: application/json"
```

gives the following result:

```
{"tokens":[{"token":"kwaśniewskiego","start_offset":0,"end_offset":14,"type":"ALPHANUM>","position":0}]}
```
Even though "Kwaśniewski" is present in the Morfologik dictionary.

The reason is that the entires for proper names in Morfologik are capitalized and when the tokens are lowercased, they are not found in the dictionary. The solution is a modified Morfologik with lowercased entries. I have a patched version for the dictionary in some of my repos, i.e. https://github.com/apohllo/elasticsearch-analysis-morfologik but the real solution would require changing the original JAR of Morfologik. I once contacted the authors of the library, but they were not interested in such a change.

Maybe Allegro could host a patched version of Morfologik, as it does for the ElasticSearch Morfologik Plugin?

**Comment by pbobruk** [comment]
Hi,

I checked that you do not have to use a lowercase filter, because morfologik_stem filter already tests both: original version and lowercase version of term.

MorfologikFilter:
``` 
if (!keywordAttr.isKeyword() && 
          (lookupSurfaceForm(termAtt) || lookupSurfaceForm(toLowercase(termAtt)))) {
...
}
```

So for names You can add Your own "capitalLetter" filter and it will do the job.

capitalLetter filter must work in the following way:
KWAŚNIEWSKIEGO => Kwaśniewskiego

**Comment by apohllo** [comment]
Hmm, well, I wasn't aware of this. I will adjust my scripts. Thanks!

**Comment by apohllo** [comment]
For the record - the available solution is still sub-optimal. 
In the case I would like to do case-insensitive search for all words (not only names), I would have to stack the `lowercase` filter **after** the `morfologik_stem`, which is kind of awkward. Don't you think?
