### ISSUE TITLE
Warning during installation

### ISSUE THREAD

**Issue by apohllo** [allegro/elasticsearch-analysis-morfologik#7]
```
Downloading pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:6.0.0 from maven central
Warning: sha512 not found, falling back to sha1. This behavior is deprecated and will be removed in a future release. Please update the plugin to use a sha512 checksum
```
Is it possible to update the SHA to use 256 bits?

**Comment by pbobruk** [comment]
Hi, 

Maven Central does not support sha512 yet :( We are waiting for that.

https://www.elastic.co/blog/sha512-checksums-for-elastic-stack-artifacts
> For versions 6.0+, Elasticsearch supports and expects SHA-512 with the file containing the hash and the filename separated by two spaces (both elements are validated). SHA-1 support is still there for non-official plugins (file containing only the hash) and will be removed from major versions in the future when Maven Central will support SHA-512 checksums.
https://issues.sonatype.org/browse/MVNCENTRAL-2859
