### ISSUE TITLE
Elasticsearch v.7

### ISSUE THREAD

**Issue by dumar** [allegro/elasticsearch-analysis-morfologik#9]
Hi,
Do you plan to update the plugin for the version 7 of Elasticsearch? (currently 7.0.1)

Thanks for your work!

**Comment by pbobruk** [comment]
Hi,

Yes, we are planning a version for 7.x but for now we are waiting for the release of https://github.com/allegro/embedded-elasticsearch for version 7.x, as the integration tests use embedded-elasticsearch.

**Comment by GotoFinal** [comment]
Then maybe using test containers would be better approach?

**Comment by pbobruk** [comment]
Hi,
Thank you very much for your contribution :-)
I've just released a new version (7.3.2).
Greetings,
Pawel
